name: event_table
description: EventTable - income and attendance tracking for workshops
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.4.0
  intl: ^0.18.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets: include .env for Flutter Web development (serves as asset).
  # WARNING: including .env exposes it in web builds. For production web use --dart-define.
  assets:
    - .env
